# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog4(object):
    def setupUi(self, Dialog4):
        Dialog4.setObjectName("Dialog4")
        Dialog4.resize(892, 459)
        self.groupBox = QtWidgets.QGroupBox(Dialog4)
        self.groupBox.setGeometry(QtCore.QRect(40, 30, 161, 171))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 40, 21, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 40, 21, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 40, 21, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 80, 21, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 80, 21, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 80, 21, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(30, 120, 21, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 120, 21, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(110, 120, 21, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog4)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 230, 61, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label = QtWidgets.QLabel(Dialog4)
        self.label.setGeometry(QtCore.QRect(20, 230, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog4)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog4)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 270, 61, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pushButton = QtWidgets.QPushButton(Dialog4)
        self.pushButton.setGeometry(QtCore.QRect(40, 310, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog4)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 370, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog4)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 30, 171, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(30, 30, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 60, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 90, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 120, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 150, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog4)
        self.groupBox_3.setGeometry(QtCore.QRect(240, 230, 281, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 30, 115, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 60, 115, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(109, 89, 161, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 30, 115, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 70, 115, 19))
        self.radioButton_9.setObjectName("radioButton_9")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog4)
        self.groupBox_5.setGeometry(QtCore.QRect(530, 30, 341, 311))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 211, 211))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 40, 71, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(260, 110, 71, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog4)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 170, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Dialog4)
        QtCore.QMetaObject.connectSlotsByName(Dialog4)

    def retranslateUi(self, Dialog4):
        _translate = QtCore.QCoreApplication.translate
        Dialog4.setWindowTitle(_translate("Dialog4", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog4", "算子数值"))
        self.label.setText(_translate("Dialog4", "系数"))
        self.label_2.setText(_translate("Dialog4", "常数或阈值"))
        self.pushButton.setText(_translate("Dialog4", "保存算子"))
        self.pushButton_2.setText(_translate("Dialog4", "装载算子"))
        self.groupBox_2.setTitle(_translate("Dialog4", "设置算子"))
        self.radioButton.setText(_translate("Dialog4", "底色效果"))
        self.radioButton_2.setText(_translate("Dialog4", "均值模糊"))
        self.radioButton_3.setText(_translate("Dialog4", "高斯模糊"))
        self.radioButton_4.setText(_translate("Dialog4", "锐化"))
        self.radioButton_5.setText(_translate("Dialog4", "浮雕"))
        self.groupBox_3.setTitle(_translate("Dialog4", "边缘检测"))
        self.radioButton_6.setText(_translate("Dialog4", "sobel算子"))
        self.radioButton_7.setText(_translate("Dialog4", "prewitt算子"))
        self.groupBox_4.setTitle(_translate("Dialog4", "边缘方向"))
        self.radioButton_8.setText(_translate("Dialog4", "垂直"))
        self.radioButton_9.setText(_translate("Dialog4", "水平"))
        self.groupBox_5.setTitle(_translate("Dialog4", "预览图片"))
        self.pushButton_3.setText(_translate("Dialog4", "预览图像"))
        self.pushButton_4.setText(_translate("Dialog4", "恢复图像"))
        self.pushButton_5.setText(_translate("Dialog4", "确定"))

